### ISSUE TITLE
Where is Firefox add-on version?

### ISSUE THREAD

**Issue by mfcc64** [Shimmermare/NotYetAV1#1]

**Comment by Shimmermare** [comment]
There's no at the time. The code should work though.

**Comment by primeos** [comment]
For Firefox this can also be achieved without an add-on by simply setting `media.av1.enabled` to `false` in `about:config` ;)

@Shimmermare thanks for the Chromium add-on. I really like the simplicity :)

**Comment by Shimmermare** [comment]
@primeos thanks. This is closed then.
