### ISSUE TITLE
cannot work on the new decode avc1

### ISSUE THREAD

**Issue by CurssedCoffin** [Shimmermare/NotYetAV1#3]
when i'm watching stream it's still avc1 instade of vp09
![image](https://user-images.githubusercontent.com/49067137/94997399-637d4f00-05dd-11eb-8918-52695d19ce64.png)
sad :(

**Comment by Shimmermare** [comment]
Hello. **avc1** is [Advanced Video Codec](https://en.m.wikipedia.org/wiki/Advanced_Video_Coding) aka h.264. AV1 is marked as **av01** on YouTube.

Did you tried other videos for vp9? If so, does your browser support vp9? Thanks.

**Comment by CurssedCoffin** [comment]
yes， I mean my browser supports vp9 and most of the videos are played with vp9
only some streams force using avc1 or h264 which makes my CPU in high load
when I just disable h264 or av1 , it says no available decode ways
I will upload a image to show that available screen

**Comment by Shimmermare** [comment]
As I said **avc1** IS h264, it can't load your CPU. **avc1** is not the same as **av1**.

**Comment by CurssedCoffin** [comment]
Thank you sincerely. I realized my mistake. I mistakenly attributed the high load of the cpu to chrome, but it was not.
